### PR TITLE
Enforce coding style

### PR DESCRIPTION
**Pull request by paulbalandan**
This PR creates a coding style ruleset for the `tattersoftware` org. I cannot link this to the in-development version in `codeigniter4/codeigniter4` because of autoloading issues. So, this copies the one in the `translations` repo and adjusted some rules to conform with PSR12.

I have not yet applied the rules into the codebase so you can tinker around the rules and check the effects. Description for the rules can be checked here: https://mlocati.github.io/php-cs-fixer-configurator/#version:3.0

### CODE REVIEW

**Comment by MGatner** [comment]
This is awesome! Thanks Paul, this will make my module transition so much easier.

**Comment by MGatner** [comment]
It does not appear to have applied to the code itself. Do I do that manually? Previously I had a Compose script set up:
```
"style": "phpcbf --standard=./vendor/codeigniter4/codeigniter4-standard/CodeIgniter4 tests/ src/",
```
That way I could just run `composer style` before any commits to see/apply style changes. Is there a similar command here?

**Comment by paulbalandan** [comment]
You can add this to your scripts:

`style: php-cs-fixer fix --verbose --ansi`

**Comment by MGatner** [comment]
Thank you greatly Paul. This is now integrated into my repo templates and `Workflows` will receive it on the next update.

**Pull request closed without merging**
